spring.application.name=personal-expense-tracker
server.port=8080

spring.thymeleaf.cache=false
spring.jackson.serialization.indent-output=true

app.storage.users-file=data/users.json
app.storage.expenses-file=data/expenses.json
